---
- name: Configure httpd Server
  hosts: all
  become: yes
  tasks:
    - name: install httpd package
      package:
        name: httpd
        state: present
    - name: start httpd service
      service:
        name: httpd
        state: started
        enabled: yes