apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  reclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /pv/log
    type: DirectoryOrCreate