---
- name: Create Files and Symbolic Links
  hosts: all
  become: yes
  tasks:
    - name: create file on stapp01
      file:
        path: /opt/finance/blog.txt
        state: touch
        owner: tony
        group: tony
        mode: '0644'
      when: ansible_host=='172.16.238.10'
    - name: create file on stapp02
      file:
        path: /opt/finance/story.txt
        state: touch
        owner: steve
        group: steve
        mode: '0644'
      when: ansible_host=='172.16.238.11'
    - name: create file on stapp03
      file:
        path: /opt/finance/media.txt
        state: touch
        owner: banner
        group: banner
        mode: '0644'
      when: ansible_host=='172.16.238.12'
    - name: create symbolic link on stapp01
      file:
        src: /opt/finance
        dest: /var/www/html
        state: link
      when: ansible_host=='172.16.238.10'
    - name: create symbolic link on stapp02
      file: 
        src: /opt/finance
        dest: /var/www/html
        state: link
      when: ansible_host=='172.16.238.11'
    - name: create symbolic link on stapp03
      file:
        src: /opt/finance
        dest: /var/www/html
        state: link
      when: ansible_host=='172.16.238.12'
